### ISSUE TITLE
Put Proferssores

### ISSUE THREAD

**Issue by Leogolass** [anahperes/mini-projeto-02-modulo-01#14]
Percebemos um bug no Put de ProfessorController, o put é "bem sucedido" e retorna o professor com as alterações, porém ao fazer o GET , percebemos que o professor não foi alterado, de fato.

**Comment by anahperes** [comment]
O erro foi solucionado através da correção do método put no arquivo ProfessorServiceImpl.

A linha final de return antes constava como "return entity". Correção demonstrada no código abaixo.

 ```
@Override
    public ProfessorEntity atualizarProfessor(Long id, ProfessorEntity professorAtualizado) {
        logger.info("Atualizando Professor com o ID: {}", id);
        if (!professorRepository.existsById(id)) {
            logger.warn("Professor não encontrado com o ID: {}", id);
            throw new NotFoundException("Professor não encontrado com o ID: " + id);
        }
        professorAtualizado.setId(id);
        return professorRepository.save(professorAtualizado);
    }
```
